star pattern


```
*
* *
* * *
```

In [6]:
r = int(input("enter the number of rows: "))
for i in range(1, r+1, 1):
  for j in range(1, i+1, 1):
    print("* ", end="")
  print()

enter the number of rows: 4
*
* *
* * *
* * * *

inverted star pattern

In [9]:
r = int(input("enter the number of rows: "))
for i in range(r+1, 1, -1):
  for j in range(1, i+1 -1):
    print("*", end=" ")
  print()

enter the number of rows: 4
* * * *
* * *
* *
*


star pattern
```
    *
  * *
* * *
```

In [20]:
r = int(input("enter the number of rows: "))
for i in range(1, r+1, 1):
  for j in range(1, r+1-i, 1):
    print(" ", end="")
  for k in range(1, i+1, 1):
    print("*", end="")
  print()

enter the number of rows: 4
   *
  **
 ***
****

In [24]:
'''
***
 **
  *
'''
r = int(input("enter the number of rows: "))
for i in range(1, r+1, 1):
  for j in range(1, i, 1):
    print(" ", end="")
  for k in range(1, r-i+2, 1):
    print("*", end="")
  print()

enter the number of rows: 3
***
 **
  *

In [25]:
'''
1
1 2
1 2 3
'''
for i in range(1, 4, 1):
  for j in range(1, i+1, 1):
    print(j, end=" ")
  print()

1
1 2
1 2 3

In [37]:
'''
1
2 3
4 5 6
'''
count = 0
for i in range(1, 4, 1):
  for j in range(1, i+1, 1):
    count += 1
    print(count, end=" ")
  print()

1
2 3
4 5 6

In [32]:
'''
1
2 2
3 3 3
'''
for i in range(1, 4, 1):
  for j in range(1, i+1, 1):
    print(i, end=" ")
  print()

1
2 2
3 3 3

In [42]:
#using a for loop write a program that prints the decimal equivalet of 1/2 , 1/3, 1/4, ...., 1/N
n = int(input("enter the value of n: "))
for i in range(2, n+1, 1):
  print("1/", i, "=","{:.2f}".format(1/i), ",", end="")

enter the value of n: 10
1/ 2 = 0.50 ,1/ 3 = 0.33 ,1/ 4 = 0.25 ,1/ 5 = 0.20 ,1/ 6 = 0.17 ,1/ 7 = 0.14 ,1/ 8 = 0.12 ,1/ 9 = 0.11 ,1/ 10 = 0.10 ,

In [47]:
#write a program using a for loop that calulate a exponential. your program should ask the user for a base and an exponantial (exp) and calulate base^exp
#base = 2 to 10
#exp = 2 to 5
#for e

# Function to calculate factorial
def factorial(n):
  if n == 0:
    return 1
  else:
    return n * factorial(n-1)

# Function to calculate e^x using Taylor series
def power_of_e(x, n_terms):
  result = 0
  for i in range(n_terms):
    result += (x**i) / factorial(i)
  return result

for i in range(2, 11, 1):
  print("the exp of", i, "is: ")
  for j in range(2, 6, 1):
    print(i, "^", j, "=", i**j)
  print()

print("the power of e is: ")
for k in range(2, 6, 1):
  # Using the power_of_e function with a reasonable number of terms (e.g., 10)
  print("e ^",k, "=", "{:.2f}".format(power_of_e(k, 10)))

the exp of 2 is:
2 ^ 2 = 4
2 ^ 3 = 8
2 ^ 4 = 16
2 ^ 5 = 32

the exp of 3 is:
3 ^ 2 = 9
3 ^ 3 = 27
3 ^ 4 = 81
3 ^ 5 = 243

the exp of 4 is:
4 ^ 2 = 16
4 ^ 3 = 64
4 ^ 4 = 256
4 ^ 5 = 1024

the exp of 5 is:
5 ^ 2 = 25
5 ^ 3 = 125
5 ^ 4 = 625
5 ^ 5 = 3125

the exp of 6 is:
6 ^ 2 = 36
6 ^ 3 = 216
6 ^ 4 = 1296
6 ^ 5 = 7776

the exp of 7 is:
7 ^ 2 = 49
7 ^ 3 = 343
7 ^ 4 = 2401
7 ^ 5 = 16807

the exp of 8 is:
8 ^ 2 = 64
8 ^ 3 = 512
8 ^ 4 = 4096
8 ^ 5 = 32768

the exp of 9 is:
9 ^ 2 = 81
9 ^ 3 = 729
9 ^ 4 = 6561
9 ^ 5 = 59049

the exp of 10 is:
10 ^ 2 = 100
10 ^ 3 = 1000
10 ^ 4 = 10000
10 ^ 5 = 100000

the power of e is:
e ^ 2 = 7.39
e ^ 3 = 20.09
e ^ 4 = 54.60
e ^ 5 = 148.41