direct value taking

In [ ]:
a = 6
b = 9
c = a+b
print(c)

15

input taking as string

In [ ]:
a = input("enter first number: ")
b = input("enter another number: ")
c = a+b
print(c)

enter first number: 1
enter another number: 5
15

input taking as integer

In [ ]:
a = int(input("enter a number: "))
b = int(input("enter another number: "))
c = a+b
print(c)

enter a number: 12
enter another number: 4
16

uses of operator

In [ ]:
a = int(input("enter 1st number: "))
b = int(input("enter 2nd number: "))
c = a/b
d = a//b
e = a%b
f = a**b

print(c)
print(d)
print(e)
print(f)

enter 1st number: 9
enter 2nd number: 2
4.5
4
1
81

if else

In [ ]:
a = int(input("enter a number: "))
b = int(input("enter another number: "))

if a%b==0:
  print("the number is completely divisible!")
else:
  print("the number is not completely divisible!")

enter a number: 4
enter another number: 2
the number is completely divisible!

if elif else (grade card)

In [ ]:
marks = int(input("enter the marks: "))

if (marks<=100 and marks>=90):
  print("Grade O")
elif (marks<=89 and marks>=80):
  print("Grade E")
elif (marks<=79 and marks>=70):
  print("Grade A")
elif (marks<=69 and marks>=60):
  print("Grade B")
elif (marks<=59 and marks>=50):
  print("Grade C")
elif (marks<=49 and marks>=40):
  print("Grade D")
else:
  print("Grade F")

enter the marks: 59
Grade C

for loop
syntax : for i in range (initilization, condition, step)

In [ ]:
for i in range(1 , 11, 1):
  print(i)

1
2
3
4
5
6
7
8
9
10

In [ ]:
a = 0
for i in range(1 , 11, 1):
  a += i
  print(a)

1
3
6
10
15
21
28
36
45
55

find the sum of even and odd number upto certain range

In [ ]:
n = int(input("enter the range: "))
odd=0
even=0
for i in range (1, n+1, 2):
  odd += i
print("sum of odd numbers is",odd)
for i in range (2, n+1, 2):
  even += i
print("sum of even numbers is",even)

enter the range: 10
sum of odd numbers is 25
sum of even numbers is 30

In [1]:
n = int(input("enter the range: "))
e = 0
o = 0
for i in range (1, n+1, 1):
    if (i%2 == 0):
        e += i
    else:
        o += i
print("even number addition is", e)
print("odd number addition is", o)

enter the range: 20
even number addition is 110
odd number addition is 100